In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import xlrd

In [11]:
com_data = pd.read_excel("Lagos Annual IDSR-003 2009.xls", sheetname= "All Dxes LGAs  Annualized Cummu")
com_data.head()

,Cummulative Monthly State IDSR summary report,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57
0,NaN,State:,"Month: September , 2008",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Yobe State Cummulative IDSR summary report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,S/N,LGA,1.CSM,NaN,2. Cholera,NaN,3. Diarrhoea (Watery without blood),NaN,4. Diarrhoea (with blood),NaN,...,18. Neonatal Tetanus,NaN,19. Tuberculosis,NaN,20. Onchocerciasis,NaN,21. Yellow Fever,NaN,22. HPAI,NaN
4,NaN,NaN,C,D,C,D,C,D,C,D,...,C,D,C,D,C,D,C,D,C,D

In [12]:
com_data2 = pd.read_excel("Lagos Annual IDSR-003 2010.xls", sheetname= "All Dxes LGAs  Annualized Cummu")
com_data2.head()

,Cummulative Monthly State IDSR summary report,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57
0,NaN,State: Lagos,Month:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Lagos State Cummulative IDSR summary report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,S/N,LGA,1.CSM,NaN,2. Cholera,NaN,3. Diarrhoea (Watery without blood),NaN,4. Diarrhoea (with blood),NaN,...,18. Neonatal Tetanus,NaN,19. Tuberculosis,NaN,20. Onchocerciasis,NaN,21. Yellow Fever,NaN,22. HPAI,NaN
4,NaN,NaN,C,D,C,D,C,D,C,D,...,C,D,C,D,C,D,C,D,C,D

In [7]:
data = pd.read_excel("Lagos Annual IDSR-003 2009.xls")       
data

,ROUTINE MONTHLY NOTIFICATION FORM: IDSR 003,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 147,Unnamed: 148,Unnamed: 149,Unnamed: 150,Unnamed: 151,Unnamed: 152,Unnamed: 153,Unnamed: 154,Unnamed: 155,Unnamed: 156
0,LGA: Agege,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No. of HF/ LGAs:,NaN,No.of HF reporting:,NaN,NaN,NaN,Month:,JANUARY,NaN,Year:,...,NaN,NaN,Month:,DECEMBER,NaN,Year:,2009,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Report:,NaN,NaN,NaN
3,DISEASE,Cases out-patients,NaN,NaN,Cases in- patients,NaN,NaN,Total cases in & out patient,DEATHS,NaN,...,Cases in- patients,NaN,NaN,Total cases in & out patient,DEATHS,NaN,NaN,NaN,Cummulative,NaN
4,NaN,Less than 5yrs,5-14yrs,15yrs & above,Less than 5yrs,5-14yrs,15yrs & above,NaN,Less than 5yrs,5-14yrs,...,Less than 5yrs,5-14yrs,15yrs & above,NaN,Less than 5yrs,5-14yrs,15yrs & above,Total,Grand Total Cases,Grand Total Deaths
5,1. CSM,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,0,0,0,0,0,0,0
6,2. Cholera,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,0,0,0,0,0,0,0
7,3. Diarrhoea (Watery without blood),78,65,77,15,26,33,294,NaN,NaN,...,10,3,6,182,0,0,0,0,2773,1
8,4. Diarrhoea (with blood),NaN,NaN,4,NaN,NaN,4,8,NaN,NaN,...,2,NaN,3,21,0,0,0,0,309,0
9,5.Dracunculiasis\n(Guinea worm),NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,0,0,0,0,0,3,0
10,6. Hepatitis B,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,0,0,0,0,0,21,0
11,7. HIV/AIDS,NaN,NaN,4,NaN,NaN,4,8,NaN,NaN,...,NaN,NaN,1,2,0,0,0,0,527,2
12,8. Viral hemorrhagic fever (e.g. Lassa Fever),NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,0,0,0,0,0,0,0
13,9. Leprosy,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,0,0,0,0,0,1,0
14,10. Lymphatic Filariasis,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,0,0,0,0,0,31,0
15,11a) Malaria,1014,913,983,112,132,157,3311,NaN,NaN,...,28,71,72,3021,0,0,0,0,45059,3
16,11b) Malaria (severe),999,697,1184,93,85,86,3144,NaN,NaN,...,28,39,45,2270,0,0,0,0,31176,0
17,11c) Malaria (Pregnant Women),NaN,NaN,212,NaN,NaN,94,306,NaN,NaN,...,NaN,NaN,25,108,0,0,0,0,1945,0
18,12. Measles,2,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,...,NaN,NaN,NaN,2,0,0,0,0,11,0
19,13. Pertussis,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,0,0,0,0,0,0,0
20,14. Plague,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,0,0,0,0,0,0,0
21,15. Pneumonia,8,8,13,11,6,4,50,NaN,NaN,...,1,3,2,28,0,0,0,0,697,2
22,16. Poliomyelitis(AFP),3,NaN,NaN,NaN,NaN,NaN,3,0,0,...,0,0,0,0,0,0,0,0,7,0
23,STIs: \n17a). Vaginal discharge,NaN,NaN,22,NaN,NaN,NaN,22,NaN,NaN,...,NaN,NaN,NaN,29,0,0,0,0,716,0
24,17b) Genital Ulcer,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,6,0,0,0,0,45,0
25,17c) Urethral discharge,NaN,NaN,3,NaN,NaN,NaN,3,NaN,NaN,...,NaN,NaN,NaN,7,0,0,0,0,291,0
26,17d) Others STIs,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,0,0,0,0,0,152,0
27,18. Neonatal Tetanus,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,0,0,0,0,0,0,0
28,19. Tuberculosis,14,21,27,NaN,NaN,3,65,NaN,NaN,...,NaN,NaN,NaN,32,0,0,0,0,2636,0
29,20. Onchocerciasis,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,0,0,0,0,0,0,0
30,21. Yellow Fever,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,0,0,0,0,0,0,0
31,22. HPAI,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,0,0,0,0,0,0,0

In [19]:
com_data = pd.io.parsers.read_table("Lagos Annual IDSR-003 2009.xls")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte